export const SET_LANGUAGES = "SET_LANGUAGES";
export const SET_CURRENCIES = "SET_CURRENCIES";
export const SET_SERVICES = "SET_SERVICES";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_API_ERRORS = "SET_API_ERRORS";
export const SET_API_SUCCESS = "SET_API_SUCCESS";
export const SET_SHOW_MODAL_FORM = "SET_SHOW_MODAL_FORM";
export const SET_APP_LANGUAGES = "SET_APP_LANGUAGES";
